function BER = runSDRuQPSKReceiverR(prmQPSKReceiver)

%persistent hRx radio
%if isempty(hRx)
hRx = sdruQPSKRxR( ...
 'DesiredAmplitude', 1, ...
 'ModulationOrder', prmQPSKReceiver.M, ...
 'DownsamplingFactor', prmQPSKReceiver.Downsampling, ...
 'CoarseCompFrequencyResolution',prmQPSKReceiver.CoarseCompFrequencyResolution, ...
 'PhaseRecoveryLoopBandwidth', prmQPSKReceiver.PhaseRecoveryLoopBandwidth, ...
 'PhaseRecoveryDampingFactor', prmQPSKReceiver.PhaseRecoveryDampingFactor, ...
 'TimingRecoveryLoopBandwidth', prmQPSKReceiver.TimingRecoveryLoopBandwidth, ...
 'TimingRecoveryDampingFactor', prmQPSKReceiver.PhaseRecoveryDampingFactor, ...
 'PostFilterOversampling', prmQPSKReceiver.Upsampling/prmQPSKReceiver.Downsampling, ...
 'PhaseErrorDetectorGain', prmQPSKReceiver.PhaseErrorDetectorGain, ...
 'PhaseRecoveryGain', prmQPSKReceiver.PhaseRecoveryGain, ...
 'TimingErrorDetectorGain', prmQPSKReceiver.TimingErrorDetectorGain, ...
 'TimingRecoveryGain', prmQPSKReceiver.TimingRecoveryGain, ...
 'FrameSize', prmQPSKReceiver.FrameSize, ...
 'BarkerLength', prmQPSKReceiver.BarkerLength, ...
 'MessageLength', prmQPSKReceiver.MessageLength, ...
 'SampleRate', prmQPSKReceiver.Fs, ...
 'DataLength', prmQPSKReceiver.DataLength, ...
 'ReceiverFilterCoefficients', prmQPSKReceiver.ReceiverFilterCoefficients, ...
 'DescramblerBase', prmQPSKReceiver.ScramblerBase, ...
 'DescramblerPolynomial', prmQPSKReceiver.ScramblerPolynomial, ...
 'DescramblerInitialConditions', prmQPSKReceiver.ScramblerInitialConditions,...
 'PrintOption', true);

%radio = comm.SDRuReceiver(...
% 'IPAddress', prmQPSKReceiver.Address, ...
% 'CenterFrequency', prmQPSKReceiver.USRPCenterFrequency, ...
% 'Gain', prmQPSKReceiver.USRPGain, ...
% 'DecimationFactor', prmQPSKReceiver.USRPDecimationFactor, ...
% 'FrameLength', prmQPSKReceiver.USRPFrameLength, ...
% 'OutputDataType', 'double');
 
hSpectrum = dsp.SpectrumAnalyzer(...
 'Name', 'Actual Frequency Offset',...
 'Title', 'Actual Frequency Offset', ...
 'SpectrumType', 'Power density',...
 'FrequencySpan', 'Full', ...
 'SampleRate', 200e3, ...
 'YLimits', [-130,0],...
 'SpectralAverages', 50, ...
 'FrequencySpan', 'Start and stop frequencies', ...
 'StartFrequency', -100e3, ...
 'StopFrequency', 100e3,...
 'Position', figposition([50 30 30 40]));

% Initialize variables
errorIndex=0;
%m=1;
%load ReceSignal.mat
while (true)
 %1. 从 USRP 读取 IQ 信号
 [corruptSignal, len] = step(radio);
 %corruptSignal=ReceSignal(:,m);
% m=m+1;
% len=4000;
 
 %2. 能否成功读取数据长度
 if len < prmQPSKReceiver.USRPFrameLength 
 errorIndex = errorIndex+1;
 disp ( 'Not enough samples returned!' ) ;
 disp(errorIndex)
 else
   
     if m==100
     
         break;

     end
 
% %3. 如果成功读取，画出接收信号的频谱图
% corruptSignal = corruptSignal - mean(corruptSignal); % remove DC component
% step(hSpectrum, corruptSignal); 
 
% %4. 如果成功读取，画出接收信号的星座图
% figure(1)
% plot(corruptSignal(1:SimParams.Upsampling:end),'ro')
% axis([-1 1 -1 1])
% drawnow
% 
 %5. AGC（自动增益控制）、匹配滤波后，得到 RCRxSignal，频偏纠正得到 coarseCompSignal，误码率计算得到 BER
%[RCRxSignal,coarseCompSignal,BER]= step(hRx, corruptSignal);
 [BER]= step(hRx, corruptSignal);

% % %6. 画出匹配滤波后信号的星座图
% figure(2)
% plot(RCRxSignal(1:SimParams.Upsampling:end),'go')
% axis([-1 1 -1 1])
% drawnow 
% % 
% % %7. 画出匹配滤波后信号的星座图
% figure(3)
% plot(coarseCompSignal(1:SimParams.Upsampling:end),'bo')
% axis([-1 1 -1 1])
% drawnow 
% 
 %8. 输出 BER
 fprintf('Error rate is = %f.\n',BER(1))
 end
end 
release(hRx);
%release(radio);